baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Rohith McKim'
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/content/resume/"
    weight = 2
